name: Android Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Add toolchain
      run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g codecov
    - run: yarn


    - name: Setup Gradle
      env:
        SIGNINGKEY: ${{ secrets.SIGNINGKEY }}
        KEYALIAS: ${{ secrets.ALIAS }}
        STOREPASSWORD: ${{ secrets.STOREPASSWORD }}
        KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
        COMPILATION_NUMBER: ${{ github.run_id }}
      run: cd android && chmod +x ./gradlew && chmod +x ./keystore.sh && echo ${SIGNINGKEY} | base64 --decode >> my-upload-key.keystore && mv my-upload-key.keystore app/ && ./keystore.sh

    # Build Command
    - name: Build Android Release
      run: yarn release

    - uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'nightly'
        files: |
          android/app/build/outputs/apk/release/app-release.apk
